### ISSUE TITLE
Clarify Unity integration APIs in doc

### ISSUE THREAD

**Issue by eelstork** [active-logic/activelogic-cs#5]

**Comment by slimshader** [comment]
the description on asset store talks about visual debugger but no additional info in the docs too, ideally a vide showcasing the demo and the debugger would be nice since there is no way to try it out from github source

**Comment by eelstork** [comment]
@slimshader you are correct. I notice that images showing the visual debugger are missing from the online doc. Also a video is probably the best option here so I will look into these tomorrow.
Having said that, I now offer Prolog on Github - https://github.com/active-logic/prolog - this is a good alternative for debugging and free up to 1 user per proj/org

**Comment by slimshader** [comment]
btw, maybe not the best place but I am really intrigued but this library. I love the idea od DSL for BTs, I am hoping to use it for my game prototype. To clarify tho: is Activelogic indeed "just" a BT implementation ot is it something else / more too? How does it deal with events (say compared to [NPBehave](https://github.com/meniku/NPBehave) )? Will definately tr Prolog tho not sure how it relates to Activelogic

**Comment by eelstork** [comment]
@slimshader DSL?
I find it hard to say what is 'just' a BT implementation, and what is more. However from what I know about NPBehave:
- NPBehave is doing what my first try at a BT library did. You build a sequence/selector object and add nodes. This is supported in active logic - but only intended for mutating task graphs (or subgraphs) at runtime. Normally static composites are preferred as they do the same thing with near zero syntactic and performance overhead.
- If I correctly understand how events work in NPBehave, the closest equivalent in active logic is decorators. For example if you wanted to wait 0.5 seconds, that would be `After(0.5f) ? [ PlaySound() ]` but no event is registered, only manages a countdown.
- So what is the equivalent of NPBehave's decorators? In active logic you do not need explicit tasks for inverters (use !) or conditionals; plain C# is enough, as in `status SundayRoutine() => Stroll() && (hungry ? haveABite : Go("Home"))`

Illustration in [FAQ](https://github.com/active-logic/activelogic-cs/blob/master/Doc/FAQ.md) shows how Prolog and the tree view display similar information at runtime.

Until the Unity Forum thread is up, I think the best place for general questions might be the discord server - https://discord.gg/Jn9TQRR
