### ISSUE TITLE
Gig and Task docs refer to UGig and UTask

### ISSUE THREAD

**Issue by Appleguysnake** [active-logic/activelogic-cs#77]
Unclear how UGig and UTask differ, the doc [here](https://github.com/active-logic/activelogic-cs/blob/master/Doc/Reference/Gig.md) only mentions UGig. I assume the U means Unity but the functional difference is unclear.

**Comment by eelstork** [comment]
@Appleguysnake to my knowledge the only difference is that the `U` variants inherit from `UnityEngine.MonoBehaviour` for Unity editor integration. I'll patch the doc to clarify; if time will enforce a common API through testing.
This should remain open till resolved.

**Comment by eelstork** [comment]
Fixed in #82
